import { z } from "zod";

/** SQLite-owned application record ID. IDs are generated by AUTOINCREMENT. */
export const databaseIdSchema = z.number().int().positive();
export type DatabaseId = z.infer<typeof databaseIdSchema>;
